language: android

android:
  components:
    - tools
    - build-tools-23.0.2
    - android-23
    - extra-android-m2repository

jdk: oraclejdk7

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle

before_install:
 - chmod +x gradlew

script: ./gradlew build test
