language: android

android:
  components:
    - build-tools-22.0.1
    - android-22
    - extra-android-m2repository

jdk: oraclejdk7

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle

script: ./gradlew build test